name: Deploy Vite React application to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v3
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
      # Install dependencies
      - name: Install dependencies
        run: npm i
      # Build the application
      - name: Build
        run: npm run build
      # Deploy the application to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist